# Generated by Django 4.2.2 on 2023-07-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_gender_match_match_unique_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True, verbose_name='долгота'),
        ),
    ]
